name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./app

      - name: Run Unit Tests
        run: mvn test
        working-directory: ./app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./app/target/site/jacoco/jacoco.xml

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wishlist:$(date +%s)

      - name: Dependency Check OWASP
        working-directory: ./app
        run: mvn org.owasp:dependency-check-maven:aggregate
