name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run Unit Tests and Generate Coverage Report
        run: mvn verify
        working-directory: .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./target/site/jacoco/jacoco.xml

  integration-tests:
    runs-on: ubuntu-24.04
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run Integration Tests
        run: mvn integration-test
        working-directory: .

  build-docker:
    runs-on: ubuntu-24.04
    needs: integration-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: .

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wishlist:$(date +%s)
