name: Build and Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./app

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag wishlist:$(date +%s)
